## Neuron

In [3]:
inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1.0] #Every unique input going to have weight associated with it.
bias = 2.0 #Every Unique Neron going to have a unique bias associated with it.

In [4]:
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias
output

4.8

## Layer

In [5]:
inputs = [1,2,3,2.5]

weights1 = [0.2,0.8,-0.5,1.0]
weights2 = [0.5,-0.91,0.26,-0.5]
weights3 = [-0.26,-0.27,0.17,0.87]

bias1 = 2.0
bias2 = 3.0
bias3 = 0.5

In [6]:
output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]
output

[4.8, 1.21, 2.385]

## With Vectors and Matrices

In [7]:
inputs = [1,2,3,2.5]

weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]

biases = [2.,3.,0.5]

In [8]:
layer_outputs = [] # Output of the current layer
for neuron_weights,neuron_bias in zip(weights,biases):
    neuron_output = 0
    for n_input, weight in zip(inputs,neuron_weights):
        neuron_output += n_input*weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)

In [9]:
layer_outputs

[4.8, 1.21, 2.385]

## Using Numpy

In [10]:
import numpy as np

### Single Neuron

In [11]:
inputs = [1,2,3,2.5]

weights = [0.2,0.8,-0.5,1.0]

bias = 2

In [12]:
ouput = np.dot(weights,inputs)+bias
ouput

4.8

### Layer

In [13]:
inputs = [1,2,3,2.5]

weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]

biases = [2.,3.,0.5]

In [14]:
ouput = np.dot(weights,inputs)+biases
ouput

array([4.8  , 1.21 , 2.385])

### Batches

- Paralle Computing
- Imporves Generalization

In [15]:
inputs = [[1,2,3,2.5],
         [2.0,5.0,1.0,2.0],
         [-1.5,2.7,3.3,-0.8]]

weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]

biases = [2.,3.,0.5]

In [16]:
ouput = np.dot(inputs,np.array(weights).T)+biases
ouput

array([[ 4.8  ,  1.21 ,  2.385],
       [ 7.9  , -1.29 ,  0.54 ],
       [ 1.41 ,  1.051,  0.026]])

### Multi Layer

In [17]:
inputs = [[1,2,3,2.5],
         [2.0,5.0,1.0,2.0],
         [-1.5,2.7,3.3,-0.8]]

weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]

biases = [2.,3.,0.5]

weights2 = [[0.1,-0.14,0.5],[-0.5,0.12,0.33],[-0.44,0.73,-0.13]]

biases2 = [-1,2,-0.5]

In [18]:
layer1_outputs = np.dot(inputs,np.array(weights).T)+biases
ouput = np.dot(layer1_outputs,np.array(weights2).T)+biases2
ouput

array([[ 0.5031 ,  0.53225, -2.03875],
       [ 0.2406 , -1.9266 , -4.9879 ],
       [-0.99314,  1.4297 , -0.35655]])

## Implementation as CLASS

In [19]:
np.random.seed(17)
class DenseLayer:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs,n_neurons) 
        #Actually the shape has to be n_neurons x n_inputs but to prevent transpose in further operations we changing the shape here itself
        self.biases = np.zeros((1,n_neurons))
        #Shape of Vector is 1x(Vector length)
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights)+self.biases

In [20]:
inputs = [[1,2,3,2.5],
         [2.0,5.0,1.0,2.0],
         [-1.5,2.7,3.3,-0.8]]
layer1 = DenseLayer(4,8)
layer2 = DenseLayer(8,3)

In [21]:
layer1.forward(inputs)
layer1.output

array([[ 0.25023454, -0.38223691, -0.13416752,  0.30998266, -0.74353747,
         0.55790875,  0.48858367, -0.55990688],
       [ 0.09980634, -0.61090845,  0.85867368,  0.81221281, -0.95124211,
         0.48140922,  0.49222188, -1.03244312],
       [ 0.49712044, -0.00674652,  0.22922317,  0.04401875, -0.91039718,
        -0.00794204,  0.24644824, -0.56131758]])

In [22]:
layer2.forward(layer1.output)
layer2.output

array([[ 0.17368511, -0.11351645, -0.12361427],
       [ 0.21545683, -0.34250658, -0.34327191],
       [ 0.00147678, -0.08819846, -0.0779648 ]])