## RELU

In [1]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
outputs = []

In [2]:
for i in inputs:
    if i>0:
        outputs.append(i)
    elif i<=0:
        outputs.append(0)

In [3]:
outputs

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]

In [4]:
outputs=[]
for i in inputs:
    outputs.append(max(i,0))

In [5]:
outputs

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]

### Implementation as CLASS

In [6]:
import numpy as np

In [7]:
inputs = [[1,2,3,2.5],
         [2.0,5.0,1.0,2.0],
         [-1.5,2.7,3.3,-0.8]]

In [8]:
class DenseLayer:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights)+self.biases

In [9]:
class Activation_Relu:
    def forward(self,inputs):
        self.output = np.maximum(inputs,0) 

#### Creation of Data

In [10]:
np.random.seed(17)

def create_data(points, classes):
    X = np.zeros((points*classes, 2))
    y = np.zeros(points*classes, dtype='uint8')
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0,1,points) #Radius
        t = np.linspace(class_number*4,(class_number+1)*4, points) + np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5),r*np.cos(t*2.5)]
        y[ix] = class_number
    return X,y

In [11]:
X,y = create_data(100,3)

In [12]:
layer1 = DenseLayer(2,50)
activation1 = Activation_Relu()

In [13]:
layer1.forward(X)

In [14]:
layer1.output

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.19632196e-03,  6.53010092e-05, -7.00933711e-04, ...,
        -4.57213406e-04,  2.87223625e-04, -1.39697708e-03],
       [-6.24568863e-04, -1.10321054e-04, -1.93800264e-03, ...,
         8.39722600e-04,  3.30289031e-04, -2.49799220e-03],
       ...,
       [-4.13224341e-02,  8.88955373e-03,  4.80055725e-02, ...,
        -6.53327441e-02,  1.63682403e-03,  3.29948438e-02],
       [ 5.95904082e-02,  3.12796478e-03,  1.04373957e-01, ...,
        -2.48742117e-02, -2.22749432e-02,  1.47731467e-01],
       [-9.05488583e-02,  9.48909394e-03, -3.56055220e-03, ...,
        -6.85577516e-02,  1.60622939e-02, -5.00540505e-02]])

In [15]:
activation1.forward(layer1.output)

In [16]:
activation1.output

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 6.53010092e-05, 0.00000000e+00, ...,
        0.00000000e+00, 2.87223625e-04, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        8.39722600e-04, 3.30289031e-04, 0.00000000e+00],
       ...,
       [0.00000000e+00, 8.88955373e-03, 4.80055725e-02, ...,
        0.00000000e+00, 1.63682403e-03, 3.29948438e-02],
       [5.95904082e-02, 3.12796478e-03, 1.04373957e-01, ...,
        0.00000000e+00, 0.00000000e+00, 1.47731467e-01],
       [0.00000000e+00, 9.48909394e-03, 0.00000000e+00, ...,
        0.00000000e+00, 1.60622939e-02, 0.00000000e+00]])

## Softmax (Exponentiation + Normalization)

In [17]:
layer_outputs = [4.8,1.21,2.385]

In [18]:
import math
E = math.e

In [20]:
#Exponentiation
exp_values = []
for output in layer_outputs:
    exp_values.append((E**output))

In [21]:
exp_values

[121.51041751873483, 3.353484652549023, 10.859062664920513]

In [23]:
#Normalization
norm_base = sum(exp_values)
norm_values = []
for value in exp_values:
    norm_values.append(value/norm_base)

In [24]:
norm_values

[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]

In [25]:
sum(norm_values)

0.9999999999999999

### With Numpy

In [26]:
exp_values = np.exp(layer_outputs)
norm_values = exp_values / np.sum(exp_values)
norm_values

array([0.89528266, 0.02470831, 0.08000903])

In [27]:
np.sum(norm_values)

0.9999999999999999

### As Batch

In [28]:
layer_outputs = [[4.8,1.21,2.385],
                [8.9,-1.81,0.2],
                [1.41,1.051,0.026]]

In [31]:
exp_values = np.exp(layer_outputs)

In [32]:
np.sum(exp_values)

7477.06436743819

In [35]:
np.sum(exp_values,axis=0,keepdims=True) #Sum of columns

array([[7.45757991e+03, 6.37764899e+00, 1.31068064e+01]])

In [36]:
np.sum(exp_values,axis=1,keepdims=True) #Sum of rows

array([[ 135.72296484],
       [7333.35859605],
       [   7.98280655]])

In [37]:
norm_values = exp_values / np.sum(exp_values,axis=1,keepdims=True)
norm_values

array([[8.95282664e-01, 2.47083068e-02, 8.00090293e-02],
       [9.99811129e-01, 2.23163963e-05, 1.66554348e-04],
       [5.13097164e-01, 3.58333899e-01, 1.28568936e-01]])

In [39]:
np.sum(norm_values,axis=1,keepdims=True)

array([[1.],
       [1.],
       [1.]])

### Exponential Overflow

In [40]:
np.exp(1000)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


inf

* To prevent overflow during exponentiation v = u - max(u)
* Input will be from -inf to 0
* which makes range of possibilities after exponentiation between 0 and 1

In [46]:
layer_outputs = [[4.8,1.21,2.385],
                [8.9,-1.81,0.2],
                [1.41,1.051,0.026]]

In [47]:
max_values = np.max(layer_outputs,axis=1,keepdims=True)

In [48]:
layer_outputs -= max_values

In [49]:
layer_outputs

array([[  0.   ,  -3.59 ,  -2.415],
       [  0.   , -10.71 ,  -8.7  ],
       [  0.   ,  -0.359,  -1.384]])

In [51]:
exp_values = np.exp(layer_outputs)
exp_values

array([[1.00000000e+00, 2.75983304e-02, 8.93673389e-02],
       [1.00000000e+00, 2.23206120e-05, 1.66585811e-04],
       [1.00000000e+00, 6.98374351e-01, 2.50574249e-01]])

In [52]:
norm_values = exp_values / np.sum(exp_values,axis=1,keepdims=True)
norm_values

array([[8.95282664e-01, 2.47083068e-02, 8.00090293e-02],
       [9.99811129e-01, 2.23163963e-05, 1.66554348e-04],
       [5.13097164e-01, 3.58333899e-01, 1.28568936e-01]])

In [53]:
np.sum(norm_values,axis=1,keepdims=True)

array([[1.],
       [1.],
       [1.]])

In [54]:
class Activation_Softmax:
    def forward(self,inputs):
        exp_values = np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
        norm_values = exp_values / np.sum(exp_values,axis=1,keepdims=True)
        self.output = norm_values

In [55]:
X,y = create_data(100,3)

In [57]:
layer1 = DenseLayer(2,3)
activation1 = Activation_Relu()
layer2 = DenseLayer(3,3)
activation2 = Activation_Softmax()

In [58]:
layer1.forward(X)
activation1.forward(layer1.output)

layer2.forward(activation1.output)
activation2.forward(layer2.output)

In [59]:
activation2.output

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333699, 0.33332428, 0.33333873],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33335244, 0.33328699, 0.33336057],
       [0.33335426, 0.33328151, 0.33336423],
       [0.33334197, 0.33331196, 0.33334607],
       [0.33334097, 0.33331442, 0.3333446 ],
       [0.33336737, 0.33324907, 0.33338357],
       [0.3333617 , 0.33326311, 0.3333752 ],
       [0.33340215, 0.33317193, 0.33342591],
       [0.33347094, 0.33304304, 0.33348602],
       [0.33336799, 0.33324753, 0.33338449],
       [0.33344213, 0.33308546, 0.33347241],
       [0.33356955, 0.33296819, 0.33346226],
       [0.33370911, 0.33302541, 0.33326548],
       [0.33353458, 0.33290592, 0.3335595 ],
       [0.33350001, 0.33296219, 0.3335378 ],
       [0.33357986, 0.33282637, 0.33359378],
       [0.33353117, 0.33289673, 0.33357209],
       [0.3335585 , 0.33284288, 0.33359862],
       [0.33399079, 0.33303385, 0.33297536],
       [0.33377956, 0.33278135, 0.33343909],
       [0.